site_name: Subtomo

theme:
  name: readthedocs
  search: true
  # features:
  #   - content.code.copy

nav:
- index.md
- reading.md
- team.md
- getting_started.md
- Setup:
  - Wan Lab: setup/franklin.md
  - 2024 U of M Workshop: setup/202406mich.md
- HIV Dataset Tutorial:
  - Introduction: hiv/index.md
  - Tilt-Series Preprocessing: hiv/preproc.md
  - Tilt-Series Alignment: hiv/align.md
  - Tomogram Reconstruction: hiv/recon.md
  - Particle Picking: hiv/picking.md
  - Bin 8 Subtomogram Averaging: hiv/bin8.md
  - Bin 4 Subtomogram Averaging: hiv/bin4.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    # - pymdownx.superfences
    # - pymdownx.tabbed:
    #     alternate_style: true