site_name: Subtomo

theme:
  name: mkdocs
  search: true
  # These palette options allow for light and dark modes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # These features enable copy buttons on code blocks and add prev/next nav buttons
  features:
    - content.code.copy
    - navigation.footer


nav:
- index.md
- reading.md
- team.md
- Tutorial:
  - Introduction: hiv/index.md
  - Setup: hiv/setup.md
  - Tilt-Series Preprocessing: hiv/preproc.md
  - Tilt-Series Alignment: hiv/align.md
  - Tilted CTF estimation: hiv/ctf_estimation.md
  - Tomogram Reconstruction: hiv/recon.md
  - Particle Picking: hiv/picking.md
  - Bin 8 Subtomogram Averaging: hiv/bin8.md
  - Bin 4 Subtomogram Averaging: hiv/bin4.md

# This extra JS powers the mathjax support for equation rendering
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# This extra CSS was an attempt to hide the RTD flyout menu see https://squidfunk.github.io/mkdocs-material/customization/?h=css#additional-css
# Couldn't get it working with material theme
extra_css: [stylesheets/extra.css]

markdown_extensions:
    - mdx_math
    # - pymdownx.highlight:
    #     anchor_linenums: true
    #     line_spans: __span
    #     pygments_lang_class: true
    # - pymdownx.inlinehilite
    # - pymdownx.snippets
    # - pymdownx.superfences
    # - pymdownx.tabbed:
    #     alternate_style: true

# Extra space added to footer to keep nav buttons from being hidden by RTD flyout menu
copyright: "<p><p>Tutorial written by Spencer J Rothfuss and Will Wan."
