site_name: Subtomo

nav:
- index.md
- reading.md
- team.md
- getting_started.md
- HIV Dataset (EMPIAR-10164):
  - Introduction: hiv/index.md
  - TOMOMAN Setup: hiv/setup.md
  - Tilt-Series Preprocessing: hiv/preproc.md
  - Particle Picking: hiv/picking.md
  - Bin 8 Subtomogram Averaging: hiv/bin8.md
  - Bin 4 Subtomogram Averaging: hiv/bin4.md
- Tutorial Archive: 
  - 202208 EMBO Practical: 202208_embo/index.md

theme:
  name: readthedocs
  search: true

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math